---
apiVersion: v1
kind: Service
metadata:
  name: postgresapache
  labels:
    app: postgres
spec:
  externalIPs:
    - 10.0.0.5
  ports:
    - port: 5432
  selector:
    app: postgres
    tier: postgreSQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresapache
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresapache
          env:
            - name: POSTGRES_USER
              value: apache
            - name: POSTGRES_PASSWORD
              value: apache
            - name: POSTGRES_DB
              value: apache
          ports:
            - containerPort: 5432
              name: postgresapache
          volumeMounts:
            - name: postgresapache
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresapache
          persistentVolumeClaim:
            claimName: postgres-claim
---

